<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
   <PropertyGroup>
      <bmversion>220</bmversion>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <RollForward>Major</RollForward>
      <TargetFramework>net8.0</TargetFramework>
      <Nullable>disable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
      <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
      <NoWarn>$(NoWarn);CS8600</NoWarn>
      <ApplicationIcon>webserver.ico</ApplicationIcon>
   </PropertyGroup>
   <ItemGroup>
      <Content Include="webserver.ico" />
   </ItemGroup>
   <ItemGroup>
      <PackageReference Include="NUglify" Version="1.21.17" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\BMAlbumTools\BMAlbumTools.csproj" />
   </ItemGroup>
   <ItemGroup>
      <Reference Include="BMBoolParser$(bmversion)">
         <HintPath>..\_References\BMBoolParser$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="bmcore$(bmversion)">
         <HintPath>..\_References\BMCore$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMElastic$(bmversion)">
         <HintPath>..\_References\BMElastic$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMHttp$(bmversion)">
         <HintPath>..\_References\BMHttp$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMImage$(bmversion)">
         <HintPath>..\_References\BMImage$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMQuery$(bmversion)">
         <HintPath>..\_References\BMQuery$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMWeb$(bmversion)">
         <HintPath>..\_References\BMWeb$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="BMWebService$(bmversion)">
         <HintPath>..\_References\BMWebService$(bmversion).dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
      <Reference Include="SixLabors.ImageSharp">
         <HintPath>..\_References\SixLabors.ImageSharp.dll</HintPath>
         <SpecificVersion>False</SpecificVersion>
      </Reference>
   </ItemGroup>
</Project>