<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
      <TargetFramework>net8.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <RootNamespace>Bitmanager.AlbumTools</RootNamespace>
      <bmversion>220</bmversion>
   </PropertyGroup>
   <ItemGroup>
      <Reference Include="bmcore$(bmversion)">
         <HintPath>..\..\_References\BMCore$(bmversion).dll</HintPath>
      </Reference>
   </ItemGroup>
</Project>